on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest



    steps:
      - uses: actions/checkout@v3
      - name: "Accessing Docker"
        run: docker login --username ${{ secrets.DUSER }} --password ${{ secrets.DPASS }}

      - name: Delete Docker Image
        run: docker rmi ftatimo/fatmasimage