on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest



    steps:
      - uses: actions/checkout@v3
      - name: "Accessing Docker"
        run: dcoker login --username ftatimo --password dckr_pat_BOm1uOyh-QKMqmba1MEdPce297M

