on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest



    steps:
      - uses: actions/checkout@v3
      - name: "Accessing Docker"
        run: docker login --username ${{ secrets.DUSER }} --password ${{ secrets.DPASS }}

      - name: "OUR FIRST DOCKERIMAGE HEREEE"
        run: docker build -t ${{ secrets.DUSER }}/image .

      - name: "Pushing"
        run: docker push ${{ secrets.DUSER }}/image