on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest



    steps:
      - name: "FirstAction"
        run: pwd
    
      - name: "PrintSMTH"
        run: echo Fatem
      
      - uses: actions/checkout@v3

      - name: "PrintFiles Except with dot ones"
        run: ls
